name: Python CI/CD

on:
  push:
    branches:
      - main  # Trigger tests on pushes to main
    tags:
      - 'v*'  # Trigger tests on tag pushes starting with 'v'
  pull_request:
    branches:
      - main  # Trigger tests on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Test(s)
      - name: Run tests
        run: pytest
