name: Docker Build and Push

on:
  push:
    tags:
      - 'v*' # Trigger only on tags starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract Version from Git Tag
      - name: Get version from Git tag
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t blackbeardedtaj/pdf-to-text:${{ env.version }} .
          docker tag blackbeardedtaj/pdf-to-text:${{ env.version }} blackbeardedtaj/pdf-to-text:latest

      # Step 5: Push Docker Image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push blackbeardedtaj/pdf-to-text:${{ env.version }}
          docker push blackbeardedtaj/pdf-to-text:latest
